{
 "metadata": {
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  },
  "orig_nbformat": 2,
  "kernelspec": {
   "name": "python3810jvsc74a57bd048c40bf0b7e70b78940e04778bbd07caa1b10f31c6c60770da56fea5fb44933a",
   "display_name": "Python 3.8.10 64-bit ('taichi': conda)"
  },
  "metadata": {
   "interpreter": {
    "hash": "48c40bf0b7e70b78940e04778bbd07caa1b10f31c6c60770da56fea5fb44933a"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2,
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "hello world\n"
     ]
    }
   ],
   "source": [
    "print(\"hello world\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "[Taichi] mode=release\n",
      "[Taichi] version 0.7.20, llvm 10.0.0, commit 284f75ed, win, python 3.8.10\n",
      "[Taichi] Starting on arch=cuda\n"
     ]
    }
   ],
   "source": [
    "import taichi as ti\n",
    "ti.init(arch=ti.gpu)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "\u001b[33m\u001b[1mDeprecationWarning: ti.var is deprecated. Please use ti.field instead.\n",
      "\n",
      "  File \"c:\\Users\\zeffi\\.vscode\\extensions\\ms-toolsai.jupyter-2021.6.832593372\\pythonFiles\\vscode_datascience_helpers\\..\\pyvsc-run-isolated.py\", line 30, in <module>\n",
      "    runpy.run_path(module, run_name=\"__main__\")\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 265, in run_path\n",
      "    return _run_module_code(code, init_globals, run_name,\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 97, in _run_module_code\n",
      "    _run_code(code, mod_globals, init_globals,\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\zeffi\\.vscode\\extensions\\ms-toolsai.jupyter-2021.6.832593372\\pythonFiles\\vscode_datascience_helpers\\kernel_prewarm_starter.py\", line 31, in <module>\n",
      "    runpy.run_module(module, run_name=\"__main__\", alter_sys=False)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 210, in run_module\n",
      "    return _run_code(code, {}, init_globals, run_name, mod_spec)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\traitlets\\config\\application.py\", line 845, in launch_instance\n",
      "    app.start()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 612, in start\n",
      "    self.io_loop.start()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\asyncio\\base_events.py\", line 570, in run_forever\n",
      "    self._run_once()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\asyncio\\base_events.py\", line 1859, in _run_once\n",
      "    handle._run()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\ioloop.py\", line 688, in <lambda>\n",
      "    lambda f: self._run_callback(functools.partial(callback, future))\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 814, in inner\n",
      "    self.ctx_run(self.run)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 775, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 365, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
      "    yielded = ctx_run(next, result)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 268, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
      "    yielded = ctx_run(next, result)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 543, in execute_request\n",
      "    self.do_execute(\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
      "    yielded = ctx_run(next, result)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 306, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2894, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3165, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3437, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-3-299d1a256dcc>\", line 1, in <module>\n",
      "    a=ti.var(dt=ti.f32,shape=(42,63))\n",
      "\n",
      "\u001b[0m\u001b[33m\u001b[1mDeprecationWarning: Declaring global matrices using `ti.Matrix(n, m, dt, shape)` is deprecated, use `ti.Matrix.field(n, m, dtype, shape)` instead\n",
      "\n",
      "  File \"c:\\Users\\zeffi\\.vscode\\extensions\\ms-toolsai.jupyter-2021.6.832593372\\pythonFiles\\vscode_datascience_helpers\\..\\pyvsc-run-isolated.py\", line 30, in <module>\n",
      "    runpy.run_path(module, run_name=\"__main__\")\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 265, in run_path\n",
      "    return _run_module_code(code, init_globals, run_name,\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 97, in _run_module_code\n",
      "    _run_code(code, mod_globals, init_globals,\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\zeffi\\.vscode\\extensions\\ms-toolsai.jupyter-2021.6.832593372\\pythonFiles\\vscode_datascience_helpers\\kernel_prewarm_starter.py\", line 31, in <module>\n",
      "    runpy.run_module(module, run_name=\"__main__\", alter_sys=False)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 210, in run_module\n",
      "    return _run_code(code, {}, init_globals, run_name, mod_spec)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\traitlets\\config\\application.py\", line 845, in launch_instance\n",
      "    app.start()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 612, in start\n",
      "    self.io_loop.start()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\asyncio\\base_events.py\", line 570, in run_forever\n",
      "    self._run_once()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\asyncio\\base_events.py\", line 1859, in _run_once\n",
      "    handle._run()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\ioloop.py\", line 688, in <lambda>\n",
      "    lambda f: self._run_callback(functools.partial(callback, future))\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 814, in inner\n",
      "    self.ctx_run(self.run)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 775, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 365, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
      "    yielded = ctx_run(next, result)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 268, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
      "    yielded = ctx_run(next, result)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 543, in execute_request\n",
      "    self.do_execute(\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
      "    yielded = ctx_run(next, result)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 306, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2894, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3165, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3437, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-3-299d1a256dcc>\", line 2, in <module>\n",
      "    b=ti.Vector(3,dt=ti.f32,shape=4)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\taichi\\lang\\matrix.py\", line 994, in Vector\n",
      "    return Matrix(n, 1, dt=dt, shape=shape, offset=offset, **kwargs)\n",
      "\n",
      "\u001b[0m\u001b[33m\u001b[1mDeprecationWarning: Declaring global matrices using `ti.Matrix(n, m, dt, shape)` is deprecated, use `ti.Matrix.field(n, m, dtype, shape)` instead\n",
      "\n",
      "  File \"c:\\Users\\zeffi\\.vscode\\extensions\\ms-toolsai.jupyter-2021.6.832593372\\pythonFiles\\vscode_datascience_helpers\\..\\pyvsc-run-isolated.py\", line 30, in <module>\n",
      "    runpy.run_path(module, run_name=\"__main__\")\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 265, in run_path\n",
      "    return _run_module_code(code, init_globals, run_name,\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 97, in _run_module_code\n",
      "    _run_code(code, mod_globals, init_globals,\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\zeffi\\.vscode\\extensions\\ms-toolsai.jupyter-2021.6.832593372\\pythonFiles\\vscode_datascience_helpers\\kernel_prewarm_starter.py\", line 31, in <module>\n",
      "    runpy.run_module(module, run_name=\"__main__\", alter_sys=False)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 210, in run_module\n",
      "    return _run_code(code, {}, init_globals, run_name, mod_spec)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\traitlets\\config\\application.py\", line 845, in launch_instance\n",
      "    app.start()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 612, in start\n",
      "    self.io_loop.start()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\asyncio\\base_events.py\", line 570, in run_forever\n",
      "    self._run_once()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\asyncio\\base_events.py\", line 1859, in _run_once\n",
      "    handle._run()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\ioloop.py\", line 688, in <lambda>\n",
      "    lambda f: self._run_callback(functools.partial(callback, future))\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 814, in inner\n",
      "    self.ctx_run(self.run)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 775, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 365, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
      "    yielded = ctx_run(next, result)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 268, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
      "    yielded = ctx_run(next, result)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 543, in execute_request\n",
      "    self.do_execute(\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
      "    yielded = ctx_run(next, result)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 306, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2894, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3165, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3437, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-3-299d1a256dcc>\", line 3, in <module>\n",
      "    C=ti.Matrix(2,2,dt=ti.f32,shape=(5,5))\n",
      "\n",
      "\u001b[0m\u001b[33m\u001b[1mDeprecationWarning: ti.var is deprecated. Please use ti.field instead.\n",
      "\n",
      "  File \"c:\\Users\\zeffi\\.vscode\\extensions\\ms-toolsai.jupyter-2021.6.832593372\\pythonFiles\\vscode_datascience_helpers\\..\\pyvsc-run-isolated.py\", line 30, in <module>\n",
      "    runpy.run_path(module, run_name=\"__main__\")\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 265, in run_path\n",
      "    return _run_module_code(code, init_globals, run_name,\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 97, in _run_module_code\n",
      "    _run_code(code, mod_globals, init_globals,\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\zeffi\\.vscode\\extensions\\ms-toolsai.jupyter-2021.6.832593372\\pythonFiles\\vscode_datascience_helpers\\kernel_prewarm_starter.py\", line 31, in <module>\n",
      "    runpy.run_module(module, run_name=\"__main__\", alter_sys=False)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 210, in run_module\n",
      "    return _run_code(code, {}, init_globals, run_name, mod_spec)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\traitlets\\config\\application.py\", line 845, in launch_instance\n",
      "    app.start()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 612, in start\n",
      "    self.io_loop.start()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\asyncio\\base_events.py\", line 570, in run_forever\n",
      "    self._run_once()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\asyncio\\base_events.py\", line 1859, in _run_once\n",
      "    handle._run()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\ioloop.py\", line 688, in <lambda>\n",
      "    lambda f: self._run_callback(functools.partial(callback, future))\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 814, in inner\n",
      "    self.ctx_run(self.run)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 775, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 365, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
      "    yielded = ctx_run(next, result)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 268, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
      "    yielded = ctx_run(next, result)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 543, in execute_request\n",
      "    self.do_execute(\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
      "    yielded = ctx_run(next, result)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 306, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2894, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3165, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"D:\\Apps\\Anaconda3\\envs\\taichi\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3437, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-3-299d1a256dcc>\", line 5, in <module>\n",
      "    loss=ti.var(dt=ti.f32,shape=())\n",
      "\n",
      "\u001b[0m[Taichi] materializing...\n",
      "a[3,4] =  1.0\n",
      "b[0] =  0.0 0.0 0.0\n",
      "3.0\n"
     ]
    }
   ],
   "source": [
    "a=ti.var(dt=ti.f32,shape=(42,63))\n",
    "b=ti.Vector(3,dt=ti.f32,shape=4)\n",
    "C=ti.Matrix(2,2,dt=ti.f32,shape=(5,5))\n",
    "\n",
    "loss=ti.var(dt=ti.f32,shape=())\n",
    "\n",
    "a[3,4]=1\n",
    "print(\"a[3,4] = \", a[3,4])\n",
    "\n",
    "b[2]=[6,7,8]\n",
    "print(\"b[0] = \", b[0][0], b[0][1], b[0][2])\n",
    "\n",
    "loss[None]=3\n",
    "print(loss[None])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ]
}